pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out the code from the repository'
                git branch: 'main', url: 'https://github.com/manuelcruz98/devops-23-24-JPE-1231841.git'
            }
        }
        stage('Assemble') {
            steps {
                echo 'Assembling...'
                dir('ca2/part1') {
                    script {
                        if (isUnix()) {
                            sh 'chmod +x ./gradlew'
                            sh './gradlew clean assemble'
                        } else {
                            bat '"C:\\Program Files\\Git\\bin\\bash.exe" -c "chmod +x ./gradlew"'
                            bat '"C:\\Program Files\\Git\\bin\\bash.exe" -c "./gradlew clean assemble"'
                        }
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                dir('ca2/part1') {
                    script {
                        if (isUnix()) {
                            sh './gradlew test'
                        } else {
                            bat '"C:\\Program Files\\Git\\bin\\bash.exe" -c "./gradlew test"'
                        }
                    }
                    junit 'build/test-results/test/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                echo 'Archiving...'
                dir('ca2/part1') {
                    archiveArtifacts 'build/libs/*.jar'
                }
            }
        }
    }
}
