# Começa a partir da imagem oficial do Gradle com OpenJDK 21
FROM gradle:jdk21

# Define o diretório de trabalho
WORKDIR /app

# Copia o código fonte para o diretório de trabalho
COPY . /app

# Executa o comando de build do Gradle para compilar e construir a aplicação
RUN gradle clean build

# Exponha a porta que a aplicação irá usar
EXPOSE 8080

# Define o ponto de entrada que o Docker irá executar ao iniciar o container
CMD ["java", "-jar", "build/libs/demo-0.0.1-SNAPSHOT.jar"]
